include: input: Fix unused function error
* include/linux/input/qpnp-power-on.h:81:12: error: ‘qpnp_pon_system_pwr_off’ defined but not used [-Werror=unused-function]

Signed-off-by: Henrique Pereira <pereirah2001@gmail.com>